version=0.1
 [default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bin-day-notifier"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1uj8qda10q7ms"
s3_prefix = "bin-day-notifier"
 region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

